### ISSUE TITLE
HOT ISSUE: ST.AppBuiltin

### ISSUE THREAD

**Issue by petarvukmirovic** [sneeuwballen/zipperposition#54]
@c-cube: There is an extremely strange behavior with ST.AppBuiltin:

When I call ST.app_builtin ~ty:* b l with some Builtin b and list l where Builtin is not Builtin.Not, I get back a term that is severly simplified! For eaxmple, all (dis)equalities are replacted by (dis)equivalences, and all TRUEs or FALSEs are removed if they are under Or or And.

Note however, that this should not be done if & or | have only one argument.

Strangely, when I open the app_builtin funciton it performs _NO_ simplifcations like that.
Is there any magic behavior I am not aware of?

This is very hot issue since I need to fix it before submitting the prover and I just found it out.

Thanks.

**Comment by c-cube** [comment]
Are you sure it's at the term construction and not during CNF? I don't see any smart constructor for anything but `Not` either.

**Comment by c-cube** [comment]
Note that `TypedSTerm.Form` does a lot of simplifications though, in `and_` and `or_` and the likes.

**Comment by petarvukmirovic** [comment]
I have an assertion that asserts that before and after app_builtin the builtin is the same, and this 
gets broken

**Comment by c-cube** [comment]
before and after what?

**Comment by petarvukmirovic** [comment]
before calling ST.app_builtin

**Comment by c-cube** [comment]
Can you point me to a commit, so I can try to reproduce?

**Comment by petarvukmirovic** [comment]
commit 6eeeaca24a38aa4db7cfb37d404c67233d0504aa
file Term.ml
line 1142

**Comment by c-cube** [comment]
Tests don't compile (because of testCNF, also because of `Float.of_string_opt` I had to replace with `CCFloat.of_string` because I'm on 4.06). I'll need more details to dig into this. Do you have a backtrace from the failure?

**Comment by petarvukmirovic** [comment]
@c-cube  saved me :)
