### ISSUE TITLE
Using Zipperposition with THF syntax

### ISSUE THREAD

**Issue by mcoulont** [sneeuwballen/zipperposition#82]
Hi all

I have tried to use Zipperposition with a simple THF file:
```
thf(r_decl,type,(
    r: $i > $o )).
	
thf(drinker_paradox,conjecture,
	( ? [X : $i] : ! [Y : $i] : 
		(
			( r @ X )
		=>
			( r @ Y )
		)
	)
).
```
And I get the answer : `unable to guess syntax`

This answer suggests that Zipperposition can admit as input more than one syntax.

And as Zipperposition competes (and wins) in CASC, whose syntax (in higher order logic) is THF, I guess there is a way to use Zipperposition with THF.

But I haven't found this way. Could someone tell me please ?

KR
Marc

**Comment by c-cube** [comment]
What's the file name? Zipperposition tries to guess the syntax based on the file extension (`foo.p` for TPTP).

**Comment by abentkamp** [comment]
... or alternatively you can use the option `-i tptp` to force TPTP parsing.

**Comment by mcoulont** [comment]
OK, the file was named drinker_paradox.thf

Thanks
