### ISSUE TITLE
parallel make fails

### ISSUE THREAD

**Issue by medovina** [sneeuwballen/zipperposition#92]
When building Zipperposition, 'make -j8' (which enables using up to 8 CPUs in parallel) fails:

```
$ make -j8
File "src/prover/.libzipperposition.objs/byte/_unknown_", line 1, characters 0-0:
Error: Rule failed to generate the following targets:
- src/prover/.libzipperposition.objs/byte/libzipperposition.cmi
- src/prover/.libzipperposition.objs/byte/libzipperposition.cmo
- src/prover/.libzipperposition.objs/byte/libzipperposition.cmt
...
```

On the other hand, 'make -j1' works fine.

I have '-j8' enabled by default, so when I tried building for the first time, I saw the errors above and was confused for a while.

**Comment by c-cube** [comment]
Ah, this runs several tasks in parallel _within make_. Zipperposition uses dune, so you could try `make J=8` which is going to ask _dune_ to parallelize by 8.

**Comment by abentkamp** [comment]
I think the main point is that it should not cause an error when one tries to run `make -j8` or when `-j8` is enabled by default. Since dune is doing the parallelization already, maybe we just add `NOTPARALLEL` to the makefile? I don't know how exactly that works though...

**Comment by medovina** [comment]
> I think the main point is that it should not cause an error when one tries to run `make -j8` or when `-j8` is enabled by default.

Yes, that was my point exactly.  I think that adding NOTPARALLEL would be a reasonable solution.  (It's nice to know that `make J=8` will ask dune to parallelize by 8, however just mentioning that in the documentation would be adequate in my opinion.)

**Comment by c-cube** [comment]
I didn't know about `NOPARALLEL`, that sounds very adequate indeed! All build time parallelism is handled outside of make anyway :)

**Comment by c-cube** [comment]
@medovina does this work? https://github.com/sneeuwballen/zipperposition/commit/5792fc380c87d119f8f7797aab96e5a469d9f500

**Comment by medovina** [comment]
Yes, that fixes the problem: now even make -j8 builds correctly.  Thanks for the quick fix.
