### ISSUE TITLE
Linux build fail

### ISSUE THREAD

**Issue by apease** [sneeuwballen/zipperposition#95]
I'm attempted to build on Ubuntu Linux and get the following
~/workspace/zipperposition$ make
File "src/core/Util.ml", line 15, characters 2-18:
15 |   Mtime.Span.to_us (Mtime.span start_ t)
       ^^^^^^^^^^^^^^^^
Error: Unbound value Mtime.Span.to_us

Sorry if this is a basic issue.  I'm new to OCAML too

**Comment by c-cube** [comment]
This is caused by a recent release of mtime 2.0. I'll try and add a constraint but in the mean time you can do `opam pin mtime 1.4.0` to use a compatible version.

**Comment by apease** [comment]
Thanks!  I tried that but now get other errors

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Processing  1/4: [mtime.1.4.0: dl]
⬇ retrieved mtime.1.4.0  (https://opam.ocaml.org/cache)
⊘ removed   mtime.2.0.0
∗ installed mtime.1.4.0
Done.
(base) apease@apease-ThinkPad-L14-Gen-1:~/workspace/zipperposition$ 
(base) apease@apease-ThinkPad-L14-Gen-1:~/workspace/zipperposition$ make
File "src/core/Binder.ml", line 17, characters 22-40:
17 | let compare (a:t) b = Pervasives.compare a b
                           ^^^^^^^^^^^^^^^^^^
Error: Unbound module Pervasives
...
[many more errors in Pervasives]

**Comment by c-cube** [comment]
Ah, recent ocaml version I suppose. Are you installing zipperposition from opam, or from the git repository itself?

**Comment by apease** [comment]
I'm attempting to follow the default README instructions using opam

**Comment by quicquid** [comment]
Commit d274d65 should fix this issue - if you install from a current master, it should work now.

**Comment by c-cube** [comment]
Please reopen if there are still issues on a recent-ish OCaml.
